version: "3.8"

services:
  symbol-mcp-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symbol_mcp
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RUST_LOG: info
      MCP_PORT: 3002
    ports:
      - "3002:3002"
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data:
