app = "symbolic-grounding-api"
primary_region = "sea"

[build]
dockerfile = "Dockerfile"

[env]
PORT = "3002"

# Increase HTTP timeout for SSE connections
[http_service]
internal_port = 3002
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1
# Increase timeout for long-running SSE connections
http_checks.grace_period = "120s"
http_checks.interval = "30s"
http_checks.timeout = "10s"
http_checks.method = "GET"
http_checks.path = "/message"

[http_service.concurrency]
type = "connections"
hard_limit = 500
soft_limit = 400

[[http_service.cors]]
allowed_origins = ["*"]
allowed_methods = ["GET", "POST", "OPTIONS"]
allowed_headers = ["*", "Cache-Control", "X-Requested-With", "Content-Type", "Accept", "Authorization"]
exposed_headers = ["*", "Content-Type", "Cache-Control"]
max_age = 86400

# Health checks - use TCP check since there's no HTTP health endpoint
[checks]
[checks.alive]
type = "tcp"
interval = "60s"
timeout = "30s"
grace_period = "60s"

# Additional services for different MCP server implementations
[[services]]
internal_port = 3003
protocol = "tcp"
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1

[[services.ports]]
port = 3003
handlers = ["http", "tls"]

[[services]]
internal_port = 3004
protocol = "tcp"
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1

[[services.ports]]
port = 3004
handlers = ["http", "tls"]

[[services]]
internal_port = 3005
protocol = "tcp"
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1

[[services.ports]]
port = 3005
handlers = ["http", "tls"] 